### ISSUE TITLE
release v1.1.0 plz

### ISSUE THREAD

**Issue by wadecoding** [StellaContrail/GIFPlayer#1]
Hi there!
Can you publish `v1.1.0` to release page so that we can use the drag and drop feature out of the box?

**Comment by StellaContrail** [comment]
Hi @wadecoding!

I've published the `v1.1.0` branch as a new release.
I can also merge it into the `master` branch if you like.

**Comment by wadecoding** [comment]
Thanks for publishing! A publish is fine, I didn't realize `v1.1.0` has already implemented drag and drop until I want to PR my own implementation...

Anyway, thank you for your hard work, I really like this tool.
